import {
  combatIcon,
  corrosionIcon,
  darkIcon,
  earthIcon,
  electricIcon,
  fireIcon,
  plantIcon,
  lightIcon,
  metalIcon,
  spiritIcon,
  waterIcon,
  windIcon,
  supportIcon,
  combatIconWhite,
  corrosionIconWhite,
  darkIconWhite,
  earthIconWhite,
  electricIconWhite,
  fireIconWhite,
  plantIconWhite,
  lightIconWhite,
  metalIconWhite,
  spiritIconWhite,
  waterIconWhite,
  windIconWhite,
  supportIconWhite,
} from ".";

export const ELEMENT_ICONS = {
  combat: combatIcon,
  corrosion: corrosionIcon,
  dark: darkIcon,
  earth: earthIcon,
  electric: electricIcon,
  fire: fireIcon,
  plant: plantIcon,
  light: lightIcon,
  metal: metalIcon,
  spirit: spiritIcon,
  water: waterIcon,
  wind: windIcon,
  support: supportIcon,
};

export const ELEMENT_ICONS_WHITE = {
  combat: combatIconWhite,
  corrosion: corrosionIconWhite,
  dark: darkIconWhite,
  earth: earthIconWhite,
  electric: electricIconWhite,
  fire: fireIconWhite,
  plant: plantIconWhite,
  light: lightIconWhite,
  metal: metalIconWhite,
  spirit: spiritIconWhite,
  water: waterIconWhite,
  wind: windIconWhite,
  support: supportIconWhite,
};

export const ELEMENT_ICONS_COLORS = {
  combat: "#FFB9BA",
  corrosion: "#C29FC8",
  dark: "#B1B0A7",
  earth: "#BEA99F",
  electric: "#FFF3B6",
  fire: "#dc5f2e",
  plant: "#D2FFD1",
  light: "#A9B9D5",
  metal: "#B0C8D7",
  spirit: "#937A73",
  water: "#B0E7FF",
  wind: "#E9FFFE",
  support: "#335257",
};
